# Generated by Django 4.1 on 2023-11-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centralAC_mode', models.CharField(choices=[('cool', 'cool'), ('heat', 'heat')], default='', max_length=50)),
                ('centralAC_status', models.CharField(choices=[('on', 'on'), ('off', 'off')], default='', max_length=50)),
                ('max_temperature', models.CharField(default='', max_length=50)),
                ('min_temperature', models.CharField(default='', max_length=50)),
                ('low_speed_fee', models.CharField(default='', max_length=50)),
                ('mid_speed_fee', models.CharField(default='', max_length=50)),
                ('high_speed_fee', models.CharField(default='', max_length=50)),
                ('default_target_temperature', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'centralAC',
            },
        ),
    ]
