# Generated by Django 4.1 on 2023-12-03 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('room_status', models.CharField(choices=[('empty', 'empty'), ('occupied', 'occupied')], default='', max_length=50)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='ACinfo',
            fields=[
                ('roomNo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ACPanelApp.room')),
                ('status', models.CharField(choices=[('running', 'running'), ('stopped', 'stopped'), ('waiting', 'waiting')], default='', max_length=50)),
                ('current_temperature', models.CharField(default='', max_length=50)),
                ('target_temperature', models.CharField(default='', max_length=50)),
                ('speed', models.CharField(choices=[('low', 'low'), ('mid', 'mid'), ('high', 'high')], default='', max_length=50)),
                ('fee', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'acinfo',
            },
        ),
    ]
