# Generated by Django 4.1 on 2023-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACPanelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acinfo',
            name='fee',
            field=models.CharField(default='', max_length=50),
        ),
    ]
