# Generated by Django 4.1 on 2023-12-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACPanelApp', '0002_acinfo_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('empty', 'empty'), ('occupied', 'occupied')], default='', max_length=50),
        ),
    ]
